### ISSUE TITLE
Doesn't work

### ISSUE THREAD

**Issue by Allamaris0** [hansalemaos/auto_download_undetected_chromedriver#3]
I used the example script and I got the error:

`Traceback (most recent call last):
  File "C:/Users/x/PycharmProjects/x/download_driver.py", line 1, in <module>
    from auto_download_undetected_chromedriver import download_undetected_chromedriver
  File "C:\Users\x\PycharmProjects\x\venv\lib\site-packages\auto_download_undetected_chromedriver\__init__.py", line 14, in <module>
    from flatten_any_dict_iterable_or_whatsoever import fla_tu
  File "C:\Users\x\PycharmProjects\x\venv\lib\site-packages\flatten_any_dict_iterable_or_whatsoever\__init__.py", line 537, in <module>
    def flatten_nested_something_to_list_of_tuples(nested_whatever) -> list[tuple]:
TypeError: 'type' object is not subscriptable`

**Comment by hansalemaos** [comment]
Use Python >= 3.10
